echo "hello world!"
node {
    stage("code") {
        git branch: 'main', url: 'https://github.com/sdputurn/terrafrom-getting-started.git'
    }
    stage("tf initialisation") {
        dir('getting-started') {
            sh 'export AWS_PROFILE=sdputurn'
            sh 'terraform init'
        }
    }
    stage("tf plan"){
        dir('getting-started') {
            sh 'AWS_PROFILE=sdputurn terraform plan'
        }
    }
    stage("apply") {
        dir('getting-started') {
            sh 'AWS_PROFILE=sdputurn terraform plan'
        }
    }
}
